# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 943d99e0d7ecad931e318d4ac2936aa3072da394a95352b550253865420455e5650960241a1b19fa2ff1899ad3dd3bfe5f1aae9aeaca061ddc9fe4a66f7015e5

test:
  secret_key_base: 6288e834c053575087633d659bdfd1921dd5f57eb1bd12e38033765a32bf4700dc6342a4afc8235a51f4b3180cbaa96a6048d821ce4ff659f6e9048ba48a7666

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
